# -*- coding: utf-8 -*-
"""Basic-regression-project-from-scratch-EDA-and-Feature-Engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kvbwFPx32l-H6HteR2LDH5bwEtJYyNaX
"""

#Importing
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dataset = pd.read_csv('Algerian_forest_fires_dataset_UPDATE.csv', header = 1)

dataset.head() #To see the first few rows of the dataset.

#We will create a regression model which will predict the "temperature", so output feature is "temperature".

dataset.info() #To know the data type of the columns

# Now data cleaning
# This line finds all rows in the dataset that have any missing values (NaN)
dataset[dataset.isnull().any(axis=1)]

# Set the "Region" column values for the first 123 rows (index 0 to 122) to 0
dataset.loc[:122, "Region"] = 0

# Set the "Region" column values from row 122 onwards to 1
dataset.loc[122:, "Region"] = 1

# Create a new variable 'df' as a copy of 'dataset'
df = dataset

df.info() #Checking the data type of the "Region" column.

df.head() #Seeing the new column "Region"

df[['Region']] = df[['Region']].astype(int) #Changing the data type of "Region" column from float to integer

df.info() #Checking the data type of the "Region" column.

#Checking the null value
df.isnull().sum()

# Removing all rows that have any missing values (NaN) from the dataframe
# Then reset the row indices so they start from 0 again
df = df.dropna().reset_index(drop=True)

df.head() #again checking the first 5 rows

df.isnull().sum() #Checking again for the null values, clearly no null value exists now.

df.iloc[[122]]
#Clearly, the 122nd location is having the values as the column name, which is obviously not a good thing.

#Dropping the 122nd row
df = df.drop(122).reset_index(drop=True)

#Again rechecking the 122nd
df.iloc[[122]]
#now it is fine

df.columns
#Checking the column name
#Clearly, we can see the spaces in the name of the columns, which we want to remove

#Fixing the spaces in column names
df.columns = df.columns.str.strip()
df.columns
#now, spaces are removed.

df.info()

#Seeing the data type, we need to convert them to integer type

df[['month','day','year','Temperature','RH','Ws']] = df[['month','day','year','Temperature','RH','Ws']].astype(int)

df.info()
#clearly, they are now all integer (selected one)

df.head()
#Clearly, some values are in floating too, but there data type in object

#changing the other columns to float data type
objects = [features for features in df.columns if df[features].dtype == 'O']

objects
#Since keep in mind that 'classes' is categorical column, so need to be followed with encoding

for i in objects:
  if i!='Classes':
    df[i] = df[i].astype(float)
#Loop to convert the data type to float for all the columns stored in 'objects' above.

df.info()

df.describe()

df.head()

#Saving the cleaned data set
df.to_csv('Algerian_forest_fires_cleaned_dataset.csv', index=False)

#now we will perform EDA

# Drop columns that are not useful for analysis
# axis=1 means we are removing columns, not rows
df_copy = df.drop(['day', 'month', 'year'], axis=1)

df.head() #Checking if the rows are removed or not
#this one is original

df_copy.head()
#Yes, in the copied one, removed columns are not present

#Seeing the categories in classes
df_copy['Classes'].value_counts()
#Clearly, due to spaces we can see 'fire' is counted many times as separate

# Convert the Classes column to string to avoid errors
# Assign 0 if it contains 'not fire', otherwise assign 1
df_copy['Classes'] = np.where(df_copy['Classes'].astype(str).str.contains('not fire'),0,1)

df_copy.tail()
#Last 5 rows of the column when classes column are managed to show either 0 or 1

df_copy['Classes'].value_counts()

# Use a valid seaborn-like matplotlib style
plt.style.use('seaborn-v0_8')

# Plot histograms for all numerical columns
df_copy.hist(bins=50, figsize=(20, 15))

# Show the plots
plt.show()

# Calculate the percentage of each class for the pie chart

# value_counts(normalize=True) gives proportions instead of counts
# Multiply by 100 to convert proportions into percentages
percentage = df_copy['Classes'].value_counts(normalize=True) * 100

# Plotting a pie chart for the class distribution

# Labels for the pie chart categories
classlabels = ["Fire", "Not Fire"]

# Set the size of the figure
plt.figure(figsize=(12, 7))

# Create the pie chart
# percentage contains the class percentages
# labels assigns names to each slice
# autopct shows the percentage value on each slice
plt.pie(percentage, labels=classlabels, autopct="%1.2f%%")

# Add a title to the plot
plt.title("Pie Chart of Classes")

# Display the pie chart
plt.show()

#Correlation
df_copy.corr()

#Seeing the box plot, to indentify the outliers
sns.boxplot(df['FWI'], color='green')

# Convert the 'Classes' column into two text categories

# If the value contains 'not fire', label it as 'not fire'
# Otherwise, label it as 'fire'
df['Classes'] = np.where(
    df['Classes'].str.contains('not fire'),
    'not fire',
    'fire'
)

# Monthly fire analysis

# Filter the dataframe to include only rows where Region equals 1
dftemp = df.loc[df['Region'] == 1]

# Create a figure with the specified size
plt.subplots(figsize=(13, 6))

# Set the seaborn plotting style to a white grid background
sns.set_style('whitegrid')

# Create a count plot showing the number of fires per month
# x='month' puts months on the x-axis
# hue='Classes' separates fire and not-fire cases by color
# data=df specifies the dataframe used for plotting
sns.countplot(x='month', hue='Classes', data=df)

# Set the y-axis label
plt.ylabel('Number of fires', weight='bold')

# Set the x-axis label
plt.xlabel('Month', weight='bold')

# Add a title to the plot
plt.title('Monthly fire analysis', weight='bold')