# -*- coding: utf-8 -*-
"""Label-and-ordinal-encoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15X7PyFaIGelg48IFxrVandVeTSMQJ_-u
"""

#Let's first understand the issue...!

import pandas as pd
from sklearn.preprocessing import OneHotEncoder

#Create a simple dataframe
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'red', 'blue']
})

df.head()

# Import LabelEncoder from sklearn's preprocessing module
# LabelEncoder is used to convert categorical (text) labels into numeric form
from sklearn.preprocessing import LabelEncoder

# Create an instance of the LabelEncoder class
# This object will learn a mapping from unique category values to integers
lbl_encoder = LabelEncoder()

# Apply Label Encoding to the 'color' column of the DataFrame
# fit_transform() does two things:
# 1. fit()      → learns all unique values in the 'color' column
# 2. transform()→ converts each category into a numeric label
# The output is a NumPy array of encoded values
lbl_encoder.fit_transform(df[['color']])

# Transform a new categorical value ('red') into its numeric label
# using the mapping that was learned earlier during fit() or fit_transform()
# transform() DOES NOT learn new categories — it only applies the existing mapping
lbl_encoder.transform([['red']])

lbl_encoder.transform([['blue']])

lbl_encoder.transform([['green']])

# When we use Label Encoding, categories are assigned arbitrary numeric values.
# For example:
#   blue  → 0
#   green → 1
#   red   → 2

# Although these numbers are just labels, many ML models may interpret them as having an order or priority.
#
# As a result, the model might incorrectly assume:
#   red (2) > green (1) > blue (0)

# This is a problem because colors do NOT have any natural order.

#Now to deal with that we will use ordinal encoding, which will rank them.

# What is Label Encoding?
# Each unique category is assigned a unique integer.
# The numbers do have meaning.

from sklearn.preprocessing import OrdinalEncoder

# Create a sample pandas DataFrame to demonstrate an ordinal categorical variable
# The column 'size' represents an ordered category:
# small < medium < large
# Since there is a natural ranking among these values,
# this feature is suitable for Ordinal Encoding
df = pd.DataFrame({
    'size': ['small', 'medium', 'large', 'medium', 'small', 'large']
})

df

# Create an instance of OrdinalEncoder
# We explicitly define the order of categories for the 'size' feature:
# small < medium < large
# This ensures the encoder assigns numbers that respect this natural ranking
encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']])

# Apply Ordinal Encoding to the 'size' column of the DataFrame
# fit_transform() performs two steps:
# 1. fit()       → learns the defined order of categories: small < medium < large
# 2. transform() → converts each category into its corresponding numeric value
# The output is a NumPy array containing the encoded values
encoder.fit_transform(df[['size']])

#Transform
encoder.transform([['small']])