# -*- coding: utf-8 -*-
"""Data-Encoding-Nominal-or-OHE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KoTlBwW__aZfcSgASOHQplGTN8VlAS9R
"""

# What is Data Encoding?
# ML algorithms work with numbers only.
# Encoding = converting categorical/text data → numerical format.

# Types of Data
# Numerical Data – already numbers (e.g., age, salary)
# Categorical Data – non-numeric
# Nominal: no order (e.g., color: red, blue)
# Ordinal: has order (e.g., education: high school < bachelor < master < PhD)

# Nominal Data & One-Hot Encoding (OHE)
# Nominal Data
# Categorical data without order.
# Examples: Color (Red, Blue, Green), Fruit (Apple, Mango).

# One-Hot Encoding (OHE)
# Converts each category → binary vector (0 or 1).
# Each category gets its own column.
# Ensures ML algorithms don’t assume order.

# Tip: Avoid Label Encoding for nominal data → ML may assume a false order.

#Disadvantages of OHE:

# 1) High Dimensionality: Creates one column per category → many features for high-cardinality data.
# 2) Sparsity: Most entries are 0, leading to sparse matrices → inefficient storage & computation.
# 3) Not suitable for ordinal data: OHE does not capture order between categories.
# 4) Curse of Dimensionality:  Too many features can slow down models and increase risk of overfitting.

import pandas as pd
from sklearn.preprocessing import OneHotEncoder

#Creating a simple data frame
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'red', 'blue']
})

df.head()

#Creating an instance of OHE
encoder = OneHotEncoder()
# encoder is a variable that stores this instance, so we can use it to fit and transform data later.

# Fit the encoder on the 'color' column and transform it into one-hot format
encoded = encoder.fit_transform(df[['color']]).toarray()

encoded #Red -> 0,0,1 (alphabetically done)
#Blue -> 1,0,0

import pandas as pd

# Convert the one-hot encoded array into a pandas DataFrame
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

encoder_df

pd.concat([df,encoder_df],axis=1)  #See the original and encoded side by side
#And we are done now

#Now trying this on the sns preloaded dataset
import seaborn as sns
df = sns.load_dataset('tips')

#We will convert the sex column
encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['sex']]).toarray()

encoded

import pandas as pd
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

encoder_df

pd.concat([df,encoder_df],axis=1)