# -*- coding: utf-8 -*-
"""Handling-outliers-using-python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_c5bDS0FLPO2-fN-meGhugeL93ULI76H
"""

import numpy as np

# List of students' marks
lst_marks = [45, 32, 56, 77, 88, 99, 23, 56, 78, 22, 11, 98, 56, 78, 10]

# Calculate the five-number summary using NumPy quantiles
# 0.00 → minimum value
# 0.25 → first quartile (Q1)
# 0.50 → median (Q2)
# 0.75 → third quartile (Q3)
# 1.00 → maximum value
minimum, Q1, median, Q3, maximum = np.quantile(
    lst_marks, [0, 0.25, 0.50, 0.75, 1.0]
)

minimum,Q1,median,Q3,maximum

# Calculate the Interquartile Range (IQR)
# IQR is the difference between the third quartile (Q3)
# and the first quartile (Q1)
IQR = Q3 - Q1

# Print the Interquartile Range
print(IQR)

# Calculate the lower fence for outlier detection
# Any value below this is considered a potential outlier
lower_fence = Q1 - 1.5 * IQR

# Calculate the upper fence for outlier detection
# Any value above this is considered a potential outlier
upper_fence = Q3 + 1.5 * IQR

# Print the lower and upper fences
print(lower_fence, upper_fence)

#Creating box plot
import seaborn as sns

sns.boxplot(lst_marks) #box plot for lst_marks

#Adding some outliers to the old data
lst_marks = [-1000, 45, 32, 56, 77, 88, 99, 23, 56, 78, 22, 11, 98, 56, 78, 10, 1000]

sns.boxplot(lst_marks) #box plot for new lst_marks

# The Interquartile Range (IQR) is the range of the middle 50% of a dataset. It measures statistical dispersion and is calculated as:

# IQR= 𝑄3−𝑄1
# IQR= Q3−Q1

# Where:
# Q1 = First Quartile (25th percentile)
# Q3 = Third Quartile (75th percentile)

# Purpose:
# Measures the spread of the central portion of the data.
# Less sensitive to extreme values compared to range or standard deviation.
# Used for outlier detection using the formula:
# Lower Fence = Q1 − 1.5 × IQR
# Upper Fence = Q3 + 1.5 × IQR