# -*- coding: utf-8 -*-
"""handlingmissingvalues.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YV33jUv9qG5dAN3TNRs7ANCruR29-pZf
"""

#using the seaborn library
import seaborn as sns

#loading the dataset
df = sns.load_dataset('titanic')

#Top rows of the dataset
df.head()

#Checking missing values
df.isnull()
#It gives true wherever it be missing

#To see in which column how many null values are there
df.isnull().sum()

#Checking how many data points are there
df.shape

#Dropping the data, although it will lead to loss of valuable data
df.dropna().shape #Avoid this

#Dropping column which has missing values
df.dropna(axis=1)

#Imputation Missing Values
#1) Mean value Imputation

sns.histplot(df['age'],kde=True)
# It plots the distribution of age with both bars (histogram) and a smooth density curve (KDE).

#Filling the Na with mean of the age
df['Age_mean'] = df['age'].fillna(df['age'].mean())
# “Mean imputation reduces variance and can be affected by outliers; median is often safer.”

#Check the old column and new column Age_mean side by side
df[['age','Age_mean']]
#Mean imputation works well when we have normally distributed data

#2)Median Value imputation - for outliers in the dataset

#Missing values with median
df['Age_median'] = df['age'].fillna(df['age'].median())

#Check the old column and new column Age_median side by side
df[['age','Age_median']]

#3) Mode imputation - can be used with categorical values

#Seeing all the rows which have NaN in embarked column
df[df['embarked'].isnull()] #Missing data completely at random

df['embarked'].unique()
# It shows all distinct categories (and missing values) in the embarked column.

df['embarked'].notna()
# It checks which values in embarked are present (not NaN) and returns True/False for each row.

mode_value = df[df['embarked'].notna()]['embarked'].mode()[0]
# It finds the most frequent non-missing value in the embarked column and stores it in mode_value.

df['embarked_mode'] = df['embarked'].fillna(mode_value)
# It fills the missing values in the embarked column with the mode value.

df[['embarked','embarked_mode']]

df['embarked_mode'].isnull().sum()
# It counts how many NaN values are present in the embarked_mode column.

df['embarked'].isnull().sum()
# It returns the total number of NaN values in the embarked column.