# -*- coding: utf-8 -*-
"""Support-vector-classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EkdgW90G7RQ4G_ryAfWo-_wJ6ADjID1f
"""

#Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# What does the code do:
# This code generates a synthetic dataset for a binary classification problem.
# It creates input features (X) and corresponding class labels (y) using scikit-learn.

# Why we did this:
# We use this code to create sample data when real-world data is not available.
# It helps in learning, testing, and visualizing machine learning classification models.

# What does the parameter specify:
# n_samples=1000 -> Generates 1000 data points (rows).
# n_features=2 -> Each data point has 2 input features (columns).
# n_classes=2 -> There are 2 output classes (binary classification).
# n_redundant=0 -> No feature is redundant; all features carry unique information.
# n_clusters_per_class=1 -> Each class forms one cluster of data points.

# What will be the output:
# X -> A NumPy array of shape (1000, 2) containing the feature values.
# y -> A NumPy array of shape (1000,) containing class labels (0 or 1).

# How to interpret the result:
# Each row in X represents one sample with two features.
# Each value in y is the class label for the corresponding row in X.
# The dataset can be used to train and evaluate binary classification models.

# Creating the dataset
from sklearn.datasets import make_classification
X, y = make_classification(
    n_samples=1000,
    n_features=2,
    n_classes=2,
    n_redundant=0,
    n_clusters_per_class=1
)

X

y

# What does this code do:
# This code creates a scatter plot of the two features in X
# and colors the points based on their class labels (y).

# Why we use this alternative:
# seaborn no longer supports passing x and y as positional arguments.
# So we explicitly define x and y using keyword arguments.

# What the parameters specify:
# pd.DataFrame(X) -> Converts X into a DataFrame so columns can be referenced.
# x=0 -> Uses the first feature as the x-axis.
# y=1 -> Uses the second feature as the y-axis.
# hue=y -> Colors the points according to their class labels.

# What will be the output:
# A scatter plot identical to the original intention.
# Points are colored based on class 0 or class 1.

# How to interpret the result:
# Same-colored points belong to the same class.
# Separation between colors shows how well the classes differ.

# Alternative that works and gives the same result
sns.scatterplot(x=pd.DataFrame(X)[0], y=pd.DataFrame(X)[1], hue=y)

# What does the code do:
# This code is intended to split the dataset into training and testing sets.
# Part of the data should be used to train the model, and the rest to test it.

# Why we did this:
# Without a train-test split, model evaluation is meaningless.
# Testing on the same data you trained on gives overly optimistic,
# usually misleading results.

# What does the parameter specify:
# X -> Feature matrix (input data).
# y -> Target labels (output classes).
# test_size=0.25 -> 25% of the data is reserved for testing, 75% for training.
# random_state -> A fixed seed to make the split reproducible.

# What is wrong with this code:
# `random_state10` is NOT a valid parameter.
# Python interprets it as a variable name, which does not exist.
# This will immediately raise a NameError and the code will fail.

# What will be the output (as written):
# No output at all.
# The code will crash with a NameError before doing any split.

# How to interpret the result:
# There is no result to interpret because the split never happens.
# This is a common, fragile mistake—one missing '=' breaks the entire pipeline.

# Corrected code (this will actually work):
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=10
)

# What does the code do:
# This code creates a Support Vector Machine (SVM) classifier
# with a linear kernel and trains it using the training data only.

# Why we did this:
# We train the model only on the training set so that
# we can later evaluate its performance on unseen test data.
# This helps measure how well the model generalizes.

# What does the parameter specify:
# SVC -> Support Vector Classifier from scikit-learn.
# kernel='linear' -> Uses a straight-line (linear) decision boundary.
# X_train -> Training input features.
# y_train -> Training class labels.

# What will be the output:
# The fit() method does not return visible output.
# It trains the model and stores learned parameters inside the svc object.

# How to interpret the result:
# The trained model (svc) has learned a separating line
# between the two classes based on training data.
# You can now use svc.predict() to make predictions on test data
# or visualize the decision boundary.

from sklearn.svm import SVC
svc = SVC(kernel='linear')
svc.fit(X_train, y_train)

# What does the code do:
# This code uses the trained SVM model to predict class labels
# for the test dataset (X_test).

# Why we did this:
# Predictions on test data allow us to evaluate how well the model
# performs on unseen data that was not used during training.

# What does the parameter specify:
# svc -> The trained Support Vector Machine model.
# predict() -> A method that assigns a class label to each input sample.
# X_test -> Test feature data on which predictions are made.

# What will be the output:
# y_pred -> A NumPy array containing predicted class labels (0 or 1).
# The printed output will be a list of predictions for each test sample.

# How to interpret the result:
# Each value in y_pred corresponds to one sample in X_test.
# Compare y_pred with y_test to check model accuracy.
# Matching values indicate correct predictions; mismatches indicate errors.

# Predictions
y_pred = svc.predict(X_test)
y_pred

# What does the code do:
# This code evaluates the performance of the trained classification model.
# It calculates and displays the confusion matrix and the classification report.

# Why we did this:
# Accuracy alone is not enough to understand model performance.
# These metrics show how well the model predicts each class
# and where it makes mistakes.

# What does the parameter specify:
# confusion_matrix(y_test, y_pred) ->
#   Compares true labels (y_test) with predicted labels (y_pred)
#   and summarizes the results in a matrix.
# classification_report(y_test, y_pred) ->
#   Generates detailed metrics including precision, recall,
#   F1-score, and support for each class.

# What will be the output:
# Confusion Matrix:
#   A 2×2 matrix showing:
#   [[True Negatives, False Positives],
#    [False Negatives, True Positives]]
#
# Classification Report:
#   A text report displaying precision, recall, F1-score,
#   and number of samples for each class, plus overall accuracy.

# How to interpret the result:
# Confusion Matrix:
#   Diagonal values represent correct predictions.
#   Off-diagonal values represent misclassifications.
#
# Classification Report:
#   Precision -> How many predicted positives were actually correct.
#   Recall -> How many actual positives were correctly identified.
#   F1-score -> Balance between precision and recall.
#   Higher values indicate better model performance.

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# What does the code do:
# This code creates a Support Vector Machine (SVM) classifier
# using the RBF (Radial Basis Function) kernel and trains it
# on the training dataset.

# Why we did this:
# A linear model may not perform well if the data is not linearly separable.
# The RBF kernel allows the model to learn non-linear decision boundaries,
# making it more flexible and powerful.

# What does the parameter specify:
# SVC -> Support Vector Classifier from scikit-learn.
# kernel='rbf' -> Uses the Radial Basis Function kernel to model non-linear patterns.
# X_train -> Training input features.
# y_train -> Training class labels.

# What will be the output:
# The fit() method produces no visible output.
# It trains the RBF-SVM and stores the learned model inside the `rbf` object.

# How to interpret the result:
# The trained RBF model has learned a curved decision boundary.
# It can capture complex relationships in the data.
# You can now use rbf.predict() to make predictions on test data
# and compare its performance with the linear SVM.

rbf = SVC(kernel='rbf')
rbf.fit(X_train, y_train)

# What does the code do:
# This code uses the trained RBF-kernel SVM model
# to predict class labels for the test dataset.

# Why we did this:
# We make predictions on test data to evaluate how well
# the non-linear SVM generalizes to unseen samples.

# What does the parameter specify:
# rbf -> The trained Support Vector Machine model with RBF kernel.
# predict() -> Method that assigns a class label to each input sample.
# X_test -> Feature data reserved for testing.

# What will be the output:
# y_pred -> A NumPy array containing predicted class labels (0 or 1).
# Printing y_pred shows the predicted class for each test sample.

# How to interpret the result:
# Each value in y_pred corresponds to one row in X_test.
# Compare y_pred with y_test to evaluate model accuracy.
# Differences indicate misclassified points.

# Predictions
y_pred = rbf.predict(X_test)
y_pred

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
#Clearly, the accuracy has decreased by 0.2

# What does the code do:
# This code trains a Support Vector Machine (SVM) classifier
# using a polynomial kernel and evaluates its performance on the test set.

# Why we did this:
# Polynomial kernels allow the model to learn non-linear decision boundaries
# of varying complexity depending on the degree of the polynomial.
# This can help capture more complex patterns in the data.

# What does the parameter specify:
# SVC -> Support Vector Classifier from scikit-learn.
# kernel='poly' -> Uses a polynomial kernel for non-linear separation.
# X_train, y_train -> Training features and labels.
# X_test -> Test features to make predictions.
# y_test -> True labels for comparison.
# y_pred2 -> Predicted labels from the polynomial SVM.

# What will be the output:
# confusion_matrix(y_test, y_pred2) ->
#   Shows true positives, true negatives, false positives, and false negatives.
# classification_report(y_test, y_pred2) ->
#   Displays precision, recall, F1-score, and support for each class.

# How to interpret the result:
# Confusion Matrix:
#   Diagonal elements indicate correct predictions.
#   Off-diagonal elements indicate misclassifications.
# Classification Report:
#   Precision -> Fraction of correctly predicted positives.
#   Recall -> Fraction of actual positives correctly predicted.
#   F1-score -> Balance between precision and recall.
#   Support -> Number of true samples for each class.
# Higher scores indicate better performance, and comparing with linear or RBF SVM
# can help decide which kernel works best for this dataset.

from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

# Train polynomial kernel SVM
polynomial = SVC(kernel='poly')
polynomial.fit(X_train, y_train)

# Make predictions
y_pred2 = polynomial.predict(X_test)

# Evaluate the model
print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2))

#Hyperparameter tuning with SVC

# What does the code do:
# This code defines a parameter grid for hyperparameter tuning
# of an SVM model using GridSearchCV.
# It specifies multiple values for 'C' and 'gamma' to test,
# and fixes the kernel as 'rbf'.

# Why we did this:
# GridSearchCV systematically tests all combinations of the specified parameters
# to find the best-performing SVM model on the training data.
# This helps improve model performance by tuning hyperparameters.

# What does the parameter specify:
# param_grid -> A dictionary containing hyperparameters to try:
#   'C' -> Regularization parameter. Higher C = less margin violations, stricter separation.
#   'gamma' -> Kernel coefficient for RBF. Higher gamma = the model fits more closely to training data.
#   'kernel' -> Type of SVM kernel to use. Here it is fixed to 'rbf' for non-linear boundaries.

# What will be the output:
# This line only defines the parameter grid.
# No model is trained yet and no results are produced.

# How to interpret the result:
# This dictionary will later be used in GridSearchCV.
# Each combination of C and gamma will be evaluated.
# The combination that gives the best cross-validated performance will be selected.
from sklearn.model_selection import GridSearchCV

param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
    'kernel': ['rbf']
}

# What does the code do:
# This code performs a grid search to find the best hyperparameters for an SVM model.
# It trains multiple SVMs with different combinations of 'C' and 'gamma' values
# using 5-fold cross-validation and selects the best-performing model.

# Why we did this:
# Hyperparameters like 'C' and 'gamma' significantly affect SVM performance.
# GridSearchCV automates the search for the optimal combination to improve accuracy
# and generalization on unseen data.

# What does the parameter specify:
# SVC() -> The Support Vector Classifier we want to optimize.
# param_grid=param_grid -> Dictionary of hyperparameter values to try.
# refit=True -> After finding the best parameters, refit the model on the full training set.
# cv=5 -> Uses 5-fold cross-validation to evaluate each combination of parameters.
# verbose=3 -> Prints detailed progress messages while running.

# What will be the output:
# grid.fit() trains multiple models for all combinations of C and gamma.
# It prints progress because verbose=3.
# After fitting, grid.best_params_ will contain the best hyperparameters.
# grid.best_estimator_ will contain the model trained with those best parameters.

# How to interpret the result:
# The best combination of 'C' and 'gamma' can be retrieved using grid.best_params_.
# The model stored in grid can now be used to make predictions on test data.
# This model should perform better than an SVM with default parameters.

from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

grid = GridSearchCV(
    SVC(),
    param_grid=param_grid,
    refit=True,
    cv=5,
    verbose=3
)
grid.fit(X_train, y_train)

# What does the code do:
# This code retrieves the best combination of hyperparameters
# found by GridSearchCV after evaluating all parameter combinations.

# Why we did this:
# We want to know which values of 'C' and 'gamma' (for RBF SVM)
# gave the best performance on the training set with cross-validation.
# This helps us select the optimal model configuration.

# What does the parameter specify:
# grid -> The GridSearchCV object that has already been fitted.
# best_params_ -> An attribute of GridSearchCV that stores the best hyperparameter values.

# What will be the output:
# A dictionary containing the hyperparameters that performed the best.
# Example: {'C': 10, 'gamma': 0.01, 'kernel': 'rbf'}

# How to interpret the result:
# Each key-value pair in the dictionary shows the optimal setting.
# You can use these values to refit an SVM model manually if needed,
# or rely on GridSearchCV's refitted model for predictions.

# Retrieve best hyperparameters
grid.best_params_

# What does the code do:
# This code uses the best SVM model found by GridSearchCV
# to make predictions on the test dataset and evaluates its performance.

# Why we did this:
# After finding the optimal hyperparameters, we want to see
# how the model performs on unseen data (X_test).
# This confirms whether hyperparameter tuning improved accuracy.

# What does the parameter specify:
# grid -> The fitted GridSearchCV object (refit=True automatically trains the best model).
# predict(X_test) -> Uses the best model to assign class labels to test samples.
# y_pred4 -> Stores the predicted labels for the test set.
# confusion_matrix(y_test, y_pred4) -> Compares true labels vs predictions.
# classification_report(y_test, y_pred4) -> Provides precision, recall, F1-score, and support.

# What will be the output:
# confusion_matrix -> A 2x2 matrix showing True Negatives, False Positives,
#                     False Negatives, and True Positives.
# classification_report -> Text report showing detailed performance metrics for each class.

# How to interpret the result:
# Confusion Matrix:
#   Diagonal values = correct predictions.
#   Off-diagonal values = misclassifications.
# Classification Report:
#   Precision -> How many predicted positives were correct.
#   Recall -> How many actual positives were correctly predicted.
#   F1-score -> Balance between precision and recall.
# If your comment "#Increased by 0.1" refers to accuracy,
# it means that tuning the hyperparameters improved the model's performance
# by roughly 10% compared to the previous default SVM.

# Make predictions with the best model from GridSearchCV
y_pred4 = grid.predict(X_test)

# Evaluate the predictions
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred4))
print(classification_report(y_test, y_pred4))

