# -*- coding: utf-8 -*-
"""Target-guided-ordinal-encoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ok6FKIck5eO3uvHXI5NI_Vwa0azXMPkr
"""

#Categories are ordered based on their relationship with the target variable.
# If categories influence the target and have no natural order → use Target-Guided Ordinal Encoding

import pandas as pd

# Create a sample DataFrame
# 'city' is a categorical (nominal) feature with no natural order
# 'price' is a numerical target variable
# We will later use 'price' to learn an order for the 'city' column
# using Target-Guided Ordinal Encoding
df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

df

# Group the DataFrame by the 'city' column
# For each city, calculate the mean (average) of the target variable 'price'
# This helps us understand how each city relates to the target
# The resulting values will be used to define an order for cities
# in Target-Guided Ordinal Encoding
df.groupby('city')['price'].mean()

# Group the data by 'city' and calculate the mean of the target variable 'price'
# Convert the resulting pandas Series into a Python dictionary
# The dictionary will store the average price for each city
# This mapping is the foundation for target-guided ordinal encoding
mean_price = df.groupby('city')['price'].mean().to_dict()

# Display the dictionary
mean_price

# Map each city in the 'city' column to its corresponding
# mean price value using the 'mean_price' dictionary
# This replaces each city name with the average target value
# calculated earlier (target-guided encoding)
df['city_encoded'] = df['city'].map(mean_price)

df

# Select and display only the 'price' column (target variable)
# and the 'city_encoded' column (encoded categorical feature)
# This is useful to verify how city encoding relates to the target
df[['price', 'city_encoded']]
#These two tables can be directly used to train the model, and city column can be ignored, as it is replaced by city_encoded column
#Done .... !

#Trying myself... !

#Import the dataset
import seaborn as sns
df=sns.load_dataset('tips')

df

#Let's try to change the time on basis of total_bill column

df.groupby('time')['total_bill'].mean()

mean_price = df.groupby('time')['total_bill'].mean().to_dict()

mean_price

df['time_encoded'] = df['time'].map(mean_price)

df