# -*- coding: utf-8 -*-
"""Logistic-regression-implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQP1tFsk2XhhrkoyfWFHJNT-aWaKsqf6
"""

#Importing
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Import make_classification function to create fake classification data
from sklearn.datasets import make_classification

# Creating a synthetic (fake) dataset for classification
X, y = make_classification(
    n_samples=1000,      # total number of data points (rows)
    n_features=10,       # total number of input features (columns)
    n_classes=2,         # number of target classes (binary classification)
    random_state=42      # fixes randomness so output is always the same
)

# X will store the feature values (1000 rows, 10 columns)
# y will store the class labels (0 or 1 for each row)

X

y

# Performing train-test split to divide data into training and testing sets
from sklearn.model_selection import train_test_split  # import function to split data

# Split the dataset into training and testing data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,               # features (X) and labels (y)
    test_size=0.30,     # 30% data for testing, 70% for training
    random_state=42     # ensures the same split every time
)

# X_train, y_train → used to train the model
# X_test, y_test → used to test the model performance

# Model training using Logistic Regression
from sklearn.linear_model import LogisticRegression  # import Logistic Regression model

# Create a Logistic Regression model object
logistic = LogisticRegression()

# This model will learn patterns from X_train and y_train
# and will be used to predict class labels (0 or 1)

# Train the Logistic Regression model using training data
logistic.fit(X_train, y_train)

# The model learns the relationship between features (X_train)
# and labels (y_train) to make future predictions

# Use the trained model to predict labels for test data
y_pred = logistic.predict(X_test)

# Print the predicted class labels
print(y_pred)

# y_pred contains predicted values (0 or 1) for each test sample
# Output will be an array of 0s and 1s

# Predict the probability of each class for the test data
logistic.predict_proba(X_test)

# Returns probabilities for both classes (0 and 1)
# Each row shows: [probability_of_class_0, probability_of_class_1]

# Performance metrics to evaluate the model
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# accuracy_score → checks how many predictions are correct
# confusion_matrix → shows correct vs wrong predictions in a table
# classification_report → shows precision, recall, f1-score, and support

# Calculate the accuracy of the model
score = accuracy_score(y_test, y_pred)

# Print the accuracy score
print(score)

# Accuracy is a value between 0 and 1
# Example output: 0.87 (means 87% predictions are correct)


# Create the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Print the confusion matrix
print(cm)

# Output is a 2x2 table:
# [[TN FP]
#  [FN TP]]
# TN = True Negatives, FP = False Positives
# FN = False Negatives, TP = True Positives


# Generate detailed classification report
cr = classification_report(y_test, y_pred)

# Print the classification report
print(cr)

# Output shows precision, recall, f1-score, and support for each class (0 and 1)

# Now we perform hyperparameter tuning and cross-validation to improve the model

# Create a new Logistic Regression model for tuning
model = LogisticRegression()

# Penalty types (regularization methods) to test
penalty = ['l1', 'l2', 'elasticnet']
# l1 → helps with feature selection
# l2 → reduces large weights
# elasticnet → mix of l1 and l2

# Different values of C (regularization strength)
c_values = [100, 10, 1.0, 0.1, 0.01]
# Higher C → less regularization
# Lower C → more regularization

# Different solvers (algorithms) to train the model
solver = ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']
# Solvers control how the model finds the best weights

# Create a dictionary of hyperparameters to test
param = dict(
    penalty=penalty,   # regularization types to try
    C=c_values,        # different regularization strengths
    solver=solver      # different optimization algorithms
)

# This parameter grid will be used for hyperparameter tuning

# Import StratifiedKFold for cross-validation
from sklearn.model_selection import StratifiedKFold

# Create a Stratified K-Fold cross-validator
cv = StratifiedKFold()

# StratifiedKFold keeps the same class ratio in each fold
# This is useful for classification problems

# Grid Search Cross-Validation for hyperparameter tuning
from sklearn.model_selection import GridSearchCV  # import GridSearchCV

# Create GridSearchCV object to find the best model parameters
grid = GridSearchCV(
    estimator=model,      # Logistic Regression model to tune
    param_grid=param,     # all combinations of parameters to test
    scoring='accuracy',   # metric used to evaluate performance
    cv=cv,                 # cross-validation strategy (StratifiedKFold)
    n_jobs = -1           # use all available CPU cores
)

# GridSearchCV will train multiple models using different parameter combinations
# and select the one with the best accuracy

# Display the GridSearchCV object
grid

# This will show information about the GridSearchCV object in Jupyter/console
# It does NOT run anything yet
# You can see:
# - estimator used (Logistic Regression)
# - parameter grid
# - scoring metric
# - cross-validation strategy

# Run GridSearchCV to find the best hyperparameters using training data
grid.fit(X_train, y_train)

# The model will train multiple Logistic Regression models
# using all combinations from param_grid
# Each combination is evaluated using Stratified K-Fold cross-validation

# After this, grid will store:
# - best parameters → grid.best_params_
# - best score → grid.best_score_
# - best estimator → grid.best_estimator_

# Get the best combination of hyperparameters found by GridSearchCV
grid.best_params_

# Output will be a dictionary showing the best parameters
# Example output:
# {'C': 1.0, 'penalty': 'l2', 'solver': 'lbfgs'}
# This means GridSearchCV found that:
# - C = 1.0
# - penalty = 'l2'
# - solver = 'lbfgs'
# gives the best cross-validated accuracy

# Get the best cross-validated score from GridSearchCV
grid.best_score_

# Output will be a float between 0 and 1
# Example output: 0.88
# This means the best model achieved 88% accuracy during cross-validation

# Use the best model from GridSearchCV to predict labels for the test set
y_pred = grid.predict(X_test)

# y_pred contains predicted class labels (0 or 1) for each test sample
# Output example: [1 0 1 1 0 ...]
# This allows us to evaluate how well the tuned model performs on unseen data

# Calculate the accuracy of the tuned model on test data
score = accuracy_score(y_test, y_pred)

# Print the accuracy
print(score)
# Output will be a float between 0 and 1
# Example: 0.88 → 88% of predictions are correct

# Print detailed classification metrics
print(classification_report(y_test, y_pred))
# Shows precision, recall, f1-score, and support for each class (0 and 1)

# Print the confusion matrix
print(confusion_matrix(y_test, y_pred))
# Shows counts of:
# [[TN FP]
#  [FN TP]]
# TN = True Negatives, FP = False Positives
# FN = False Negatives, TP = True Positives

#Randomized Search CV

# Import RandomizedSearchCV for hyperparameter tuning
from sklearn.model_selection import RandomizedSearchCV

# Using the old Logistic Regression model
model = LogisticRegression()

# Create a RandomizedSearchCV object
randomcv = RandomizedSearchCV(
    estimator=model,           # Logistic Regression model to tune
    param_distributions=param, # hyperparameter options to test
    cv=5,                      # 5-fold cross-validation
    scoring='accuracy'         # metric used to evaluate performance
)

# Run RandomizedSearchCV on the training data
randomcv.fit(X_train, y_train)

# After this, randomcv contains:
# - best hyperparameters → randomcv.best_params_
# - best cross-validation score → randomcv.best_score_
# - trained model with best parameters → randomcv.best_estimator_

# Get the best cross-validated accuracy from RandomizedSearchCV
randomcv.best_score_

# Output will be a float between 0 and 1
# Example output: 0.87
# This means the best model found by RandomizedSearchCV achieved 87% accuracy
# during 5-fold cross-validation on the training data

# Get the best hyperparameters found by RandomizedSearchCV
randomcv.best_params_

# Output will be a dictionary showing the best parameters
# Example output:
# {'C': 1.0, 'penalty': 'l2', 'solver': 'lbfgs'}
# This tells us which combination of C, penalty, and solver gave the best accuracy

# Use the best model from RandomizedSearchCV to predict labels for test data
y_pred = randomcv.predict(X_test)

# y_pred contains predicted class labels (0 or 1) for each test sample
# Example output: [1 0 1 1 0 ...]
# This allows us to evaluate how well the tuned model performs on unseen test data

# Calculate the accuracy of the tuned model on test data
score = accuracy_score(y_test, y_pred)

# Print the accuracy
print(score)
# Output will be a float between 0 and 1
# Example: 0.88 → 88% of predictions are correct

# Print detailed classification metrics
print(classification_report(y_test, y_pred))
# Shows precision, recall, f1-score, and support for each class (0 and 1)

# Print the confusion matrix
print(confusion_matrix(y_test, y_pred))
# Shows counts of:
# [[TN FP]
#  [FN TP]]
# TN = True Negatives, FP = False Positives
# FN = False Negatives, TP = True Positives

# Now implementing Logistic Regression for a multiclass classification problem

# Create a synthetic dataset for classification
X, y = make_classification(
    n_samples=1000,      # total number of data points (rows)
    n_features=10,       # total number of input features (columns)
    n_informative=5,     # number of features that actually help predict the target
    n_classes=3,         # number of target classes (0, 1, 2) → multiclass
    random_state=15      # fixes randomness so output is always the same
)

# X stores the feature values (1000 rows × 10 columns)
# y stores the class labels (0, 1, or 2 for each row)

X

y

# Performing train-test split to divide data into training and testing sets
from sklearn.model_selection import train_test_split  # import function to split data

# Split the dataset into training and testing data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,               # features (X) and labels (y)
    test_size=0.30,     # 30% data for testing, 70% for training
    random_state=0      # ensures the same split every time
)

# X_train, y_train → used to train the model
# X_test, y_test → used to test the model performance
# Works the same for multiclass labels (0,1,2)

from sklearn.linear_model import LogisticRegression  # import Logistic Regression model

# Create a Logistic Regression model for multiclass classification
logistic = LogisticRegression(multi_class='ovr')
# multi_class='ovr' → One-vs-Rest strategy for multiple classes (default)
# Each class is treated as "positive" vs "all others" during training

# Train the model using the training data
logistic.fit(X_train, y_train)
# The model learns the relationship between features (X_train) and class labels (y_train)

# Predict class labels for the test set
y_pred = logistic.predict(X_test)
# y_pred contains predicted labels (0, 1, or 2) for each test sample

y_pred

# Calculate the accuracy of the multiclass Logistic Regression model
score = accuracy_score(y_test, y_pred)

# Print the accuracy
print(score)
# Output will be a float between 0 and 1
# Example: 0.85 → 85% of predictions are correct across all classes

# Print detailed classification metrics for each class
print(classification_report(y_test, y_pred))
# Shows precision, recall, f1-score, and support for each class (0, 1, 2)

# Print the confusion matrix
print(confusion_matrix(y_test, y_pred))
# Shows counts of predictions for each class:
# Rows = actual labels, Columns = predicted labels
# Example:
# [[TN0 FP0 FP1]
#  [FN0 TP1 FP2]
#  [FN1 FN2 TP2]]
# Each row corresponds to the true class
# Each column corresponds to predicted class

#Now logistic regression for imbalanced dataset

from collections import Counter
from sklearn.datasets import make_classification

# Create an imbalanced classification dataset
# X will store the feature values
# y will store the class labels
X, y = make_classification(
    n_samples=10000,          # Total number of data points (rows)
    n_features=2,            # Number of input features (columns)
    n_clusters_per_class=1,  # Number of clusters for each class
    n_redundant=0,           # No redundant (duplicate) features
    weights=[0.99],          # 99% of samples belong to class 0, 1% to class 1
    random_state=10          # Ensures reproducibility (same output every run)
)

X

y

# Count how many times each class label appears in y
# Counter is used to calculate the frequency of each class
Counter(y)

# Clearly, number of 0s are 9846 and number of 1s are 154

# Import seaborn library for data visualization
import seaborn as sns

# Import pandas library for data handling
import pandas as pd

# Convert X into a pandas DataFrame
df = pd.DataFrame(X)

# Create a scatter plot
# x -> first feature
# y -> second feature
# hue -> class labels (0 or 1)
sns.scatterplot(
    x=df[0],      # First feature on x-axis
    y=df[1],      # Second feature on y-axis
    hue=y         # Color points based on class label
)

# Split the dataset into training and testing sets
from sklearn.model_selection import train_test_split

# X_train -> features used to train the model
# X_test  -> features used to test the model
# y_train -> labels for training data
# y_test  -> labels for testing data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,                 # Features and labels
    test_size=0.25,       # 25% of data goes to test set
    random_state=0        # Ensures same split every time
)

# Hyperparameter tuning setup for Logistic Regression
from sklearn.linear_model import LogisticRegression

# Create a Logistic Regression model object (not trained yet)
model = LogisticRegression()

# Penalty types (regularization methods)
# l1  -> Lasso regularization (can force coefficients to zero)
# l2  -> Ridge regularization (shrinks coefficients)
# elasticnet -> Combination of l1 and l2
penalty = ['l1', 'l2', 'elasticnet']

# Inverse of regularization strength
# Higher value -> weaker regularization
# Lower value -> stronger regularization
c_values = [100, 10, 1.0, 0.1, 0.01]

# Optimization algorithms used to train Logistic Regression
solver = ['netwon-cg', 'lbfgs', 'liblinear', 'sag', 'saga']

# Class weights to handle imbalanced data
# Gives different importance to class 0 and class 1
class_weight = [
    {0: w, 1: y}
    for w in [1, 10, 50, 100]
    for y in [1, 10, 50, 100]
]

# Create a dictionary of hyperparameters
# This dictionary will be used for GridSearchCV or RandomizedSearchCV
params = dict(
    penalty=penalty,           # Regularization types to try
    C=c_values,                # Different regularization strengths
    solver=solver,             # Optimization algorithms
    class_weight=class_weight  # Class weights for imbalanced data
)

# Import GridSearchCV for hyperparameter tuning
from sklearn.model_selection import GridSearchCV

# Import StratifiedKFold to preserve class distribution in each fold
from sklearn.model_selection import StratifiedKFold

# Create a stratified k-fold cross-validation object
# This ensures each fold has the same class ratio
cv = StratifiedKFold()

# Set up GridSearchCV
# estimator -> the machine learning model (Logistic Regression)
# param_grid -> hyperparameters to try
# scoring -> metric used to evaluate model performance
# cv -> cross-validation strategy
grid = GridSearchCV(
    estimator=model,
    param_grid=params,
    scoring='accuracy',
    cv=cv
)

grid.fit(X_train, y_train)

# Display the best combination of hyperparameters
# found during Grid Search cross-validation
grid.best_params_

# Use the best model found by GridSearchCV
# to make predictions on the test dataset
y_pred = grid.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Calculate the accuracy of the model
# Accuracy = (correct predictions) / (total predictions)
score = accuracy_score(y_test, y_pred)

# Print the accuracy score
print(score)

# Print a detailed classification report
# Includes precision, recall, f1-score, and support for each class
print(classification_report(y_test, y_pred))

# Print the confusion matrix
# Shows correct vs incorrect predictions for each class
print(confusion_matrix(y_test, y_pred))

#Logistic regression with ROC curve and ROC AUC score

# ROC Curve and AUC related imports

# Used to create synthetic classification datasets (already used earlier)
from sklearn.datasets import make_classification

# Logistic Regression model (already used earlier)
from sklearn.linear_model import LogisticRegression

# Utility to split data into training and testing sets
from sklearn.model_selection import train_test_split

# roc_curve -> computes False Positive Rate and True Positive Rate
# roc_auc_score -> computes Area Under the ROC Curve
from sklearn.metrics import roc_curve, roc_auc_score

from matplotlib import pyplot

# Generate a synthetic dataset for a binary (2-class) classification problem
X, y = make_classification(
    n_samples=1000,   # Total number of data points
    n_classes=2,      # Number of target classes (0 and 1)
    random_state=1    # Ensures the same dataset is created every time
)

# Split the dataset into training and testing sets
from sklearn.model_selection import train_test_split

# X_train -> feature data for training the model
# X_test  -> feature data for testing the model
# y_train -> labels for training data
# y_test  -> labels for testing data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,               # Features and corresponding labels
    test_size=0.25,     # 25% of the data is reserved for testing
    random_state=0      # Ensures the same split every time
)

#Created a dummy model with default 0 as output
dummy_model_prob = [0 for _ in range(len(y_test))]
dummy_model_prob

# Create a basic Logistic Regression model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

# Train (fit) the model using the training data
# X_train -> features for training
# y_train -> labels for training
model.fit(X_train, y_train)

# Prediction based on probability

# Use the trained Logistic Regression model to predict probabilities for the test data
model_prob = model.predict_proba(X_test)
# model_prob[i, j] gives the probability that sample i belongs to class j
# Shape: (num_samples, num_classes)

# Take only the probabilities of class 1 for all test samples
model_prob = model_prob[:, 1]
# Shape: (num_samples,)
# Each value represents the model's estimated probability that the sample belongs to class 1

# Calculate the ROC AUC score for two models

# dummy_model_prob -> predicted probabilities from a dummy/baseline model
dummy_model_auc = roc_auc_score(y_test, dummy_model_prob)

# model_prob -> predicted probabilities from our trained Logistic Regression model
model_auc = roc_auc_score(y_test, model_prob)

# Print the AUC scores
print('Dummy Model: ROC AUC=%.3f' % (dummy_model_auc))
print('Logistic Model: ROC AUC=%.3f' % (model_auc))

# The ROC curve (Receiver Operating Characteristic) shows the trade-off between:
#   - True Positive Rate (Recall) on the y-axis
#   - False Positive Rate on the x-axis
#
# Each point on the curve corresponds to a different probability threshold
# used to classify a sample as class 1 or 0.
#
# The AUC (Area Under the Curve) is a single number summarizing model performance:
#   - 1.0 → perfect classifier
#   - 0.5 → random guessing
#   - <0.5 → worse than random
#
# Together, the ROC curve and AUC tell you how well your model distinguishes
# between the positive class (1) and negative class (0) across all thresholds.
# This is especially useful for imbalanced datasets where accuracy can be misleading.

# Calculate the ROC curve for the dummy/baseline model
# Returns:
#   - dummy_fpr: False Positive Rate at different thresholds
#   - dummy_tpr: True Positive Rate at different thresholds
#   - _: the thresholds used (not needed here)
dummy_fpr, dummy_tpr, _ = roc_curve(y_test, dummy_model_prob)

# Calculate the ROC curve for the trained Logistic Regression model
# Returns:
#   - model_fpr: False Positive Rate at different thresholds
#   - model_tpr: True Positive Rate at different thresholds
#   - _: thresholds used (not needed here)
model_fpr, model_tpr, _ = roc_curve(y_test, model_prob)

# Plot the ROC curve for both models
# 'pyplot' comes from matplotlib.pyplot
pyplot.plot(dummy_fpr, dummy_tpr, linestyle='--', label='Dummy Model')
# Plot dummy/baseline model with dashed line
# FPR on x-axis, TPR on y-axis

pyplot.plot(model_fpr, model_tpr, marker='.', label='Logistic Model')
# Plot Logistic Regression model with markers
# FPR on x-axis, TPR on y-axis

# Label the x-axis
pyplot.xlabel('False Positive Rate')

# Label the y-axis
pyplot.ylabel('True Positive Rate')

# Add a legend to identify the models
pyplot.legend()

# Display the ROC curve plot
pyplot.show()

