# -*- coding: utf-8 -*-
"""Model-training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_YnYHx6xVYkRdHXPKi5Is0xgOgSVSkWM
"""

#Importing
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Algerian_forest_fires_cleaned_dataset.csv')

df.head()
#only the 'Classes' is the categorical feature.

df.columns

#Dropping month, day and year.
df.drop(['month', 'day', 'year'], axis=1, inplace=True)

df.head() #yes, it is removed

#Seeing the things in "classes" column
df['Classes'].value_counts()
#Clearly, due to spaces fire and not fire are counted differently in themselves many times

#Encoding them
df['Classes'] = np.where(df['Classes'].str.contains('not fire'), 0, 1)

df.tail()

df['Classes'].value_counts()
#Clearly, one two types are there 0 or 1 for not fire and fire respectively

#independent and dependent features
#We are taking FWI as our output feature

# X contains all the input features (all columns except 'FWI')
X = df.drop('FWI', axis=1)

# y contains the target variable we want to predict ('FWI')
y = df['FWI']

#See which input features are there then:
X.head()

#Seeing the output feature
y

# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

# X_train, y_train are used to train the model
# X_test, y_test are used to test how well the model performs
# test_size=0.25 means 25% of the data is used for testing
# random_state=42 ensures the split is the same every time the code runs
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

#Seeing the number of rows in X_train and X_test
X_train.shape, X_test.shape

#Feature selection on basis of correlation
X_train.corr()
#If two features are highly correlated (based on threshold we defined, or by domain expert), then they will act like similar features

# Create a figure with a specific size for better visibility
plt.figure(figsize=(12, 10))

# Calculate the correlation between features in the training data
corr = X_train.corr()

# Draw a heatmap to visualize the correlation matrix
# annot=True shows the correlation values on the heatmap
sns.heatmap(corr, annot=True)

# Function to find highly correlated features based on a given threshold
def correlation(dataset, threshold):

    # Create an empty set to store names of correlated columns
    col_corr = set()

    # Calculate the correlation matrix for the dataset
    corr_matrix = dataset.corr()

    # Loop through each column in the correlation matrix
    for i in range(len(corr_matrix.columns)):

        # Compare the current column with all previous columns
        for j in range(i):

            # If the absolute correlation value is greater than the threshold
            if abs(corr_matrix.iloc[i, j]) > threshold:

                # Get the name of the correlated column
                colname = corr_matrix.columns[i]

                # Add the column name to the set
                col_corr.add(colname)

    # Return the set of highly correlated feature names
    return col_corr

# Threshold decided by a domain expert is 0.85
# This means features with correlation greater than 0.85 will be considered highly correlated
corr_features = correlation(X_train, 0.85)

#seeing the correlated features
corr_features
#Clearly, two columns are highly correlated as per our threshold value.

# Drop (remove) the highly correlated features from the training data
X_train.drop(corr_features, axis=1, inplace=True)

# Drop the same highly correlated features from the test data
# This keeps the training and test datasets consistent
X_test.drop(corr_features, axis=1, inplace=True)

#Now checking the number of rows and columns in X_train and X_test
X_train.shape, X_test.shape

# Now we perform feature scaling (standardization)
from sklearn.preprocessing import StandardScaler

# Create a StandardScaler object
scaler = StandardScaler()

# Fit the scaler on the training data and transform it
# This scales the features so they have mean = 0 and standard deviation = 1
X_train_scaled = scaler.fit_transform(X_train)

# Use the same scaler to transform the test data
# This prevents data leakage from the test set
X_test_scaled = scaler.transform(X_test)

#CHecking the X_train_scaled
X_train_scaled

# Create a figure with two subplots side by side
plt.subplots(figsize=(15,5))

# First subplot: box plot before scaling
plt.subplot(1,2,1)

# Draw a box plot for the training data before scaling
sns.boxplot(data=X_train)

# Set the title for the first plot
plt.title('X_train Before Scaling')

# Second subplot: box plot after scaling
plt.subplot(1,2,2)

# Draw a box plot for the training data after scaling
sns.boxplot(data=X_train_scaled)

# Set the title for the second plot
plt.title('X_train After Scaling')

# Display both plots
plt.show()

# Build and train the Linear Regression (LR) model
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error

# Create the Linear Regression model
linreg = LinearRegression()

# Train the model using the scaled training data
linreg.fit(X_train_scaled, y_train)

# Predict target values using the scaled test data
y_pred = linreg.predict(X_test_scaled)

# Calculate Mean Absolute Error (average prediction error)
mae = mean_absolute_error(y_test, y_pred)

# Calculate R² score (how well the model explains the variance)
score = r2_score(y_test, y_pred)

# Print evaluation results
print("Mean Absolute Error:", mae)
print("R2 Score:", score)

# Create a scatter plot to compare actual vs predicted values
plt.scatter(y_test, y_pred)

# Now, apply Lasso Regression
from sklearn.linear_model import Lasso
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error

# Create the Lasso regression model
lasso = Lasso()

# Train the model using the scaled training data
lasso.fit(X_train_scaled, y_train)

# Predict target values using the scaled test data
y_pred = lasso.predict(X_test_scaled)

# Calculate Mean Absolute Error (average absolute prediction error)
mae = mean_absolute_error(y_test, y_pred)

# Calculate R² score (how well the model fits the data)
score = r2_score(y_test, y_pred)

# Print evaluation results
print("Mean Absolute Error:", mae)
print("R2 Score:", score)

# Plot actual values vs predicted values
plt.scatter(y_test, y_pred)

# Perform cross-validation using Lasso Regression
from sklearn.linear_model import LassoCV

# Create a Lasso model with 5-fold cross-validation
lassocv = LassoCV(cv=5)

# Train the model on the scaled training data
# It automatically finds the best alpha (regularization strength)
lassocv.fit(X_train_scaled, y_train)

# Display the best alpha value chosen by LassoCV
# Alpha controls the strength of regularization
lassocv.alpha_

# Displays all alpha (regularization strength) values tested by LassoCV
lassocv.alphas_

# Shows the Mean Squared Error (MSE) values for each alpha during cross-validation
lassocv.mse_path_

y_pred = lassocv.predict(X_test_scaled)
plt.scatter(y_test,y_pred)
mae = mean_absolute_error(y_test, y_pred)
score = r2_score(y_test, y_pred)
print("Mean Absolute Error:", mae)
print("R2 Score:", score)